### ISSUE TITLE
Feature: endpoint para favoritos

### ISSUE THREAD

**Issue by alezvi** [RooftopAcademy/rooftend#111]
- Documentar la respuesta del GET, indicar la estructura de datos que devuelve
    - El endpoint "favorites" debe devolver la lista de favoritos del usuario autenticado (user_id = 1)
    - Eliminar el item_id de la respuesta
    - Enviar los datos minimos para la preview del favorito (id, titulo, precio, foto principal)
    - El nombre de la clave debe ser item
    - Debe incluir paginado de 10 items por pagina siempre, no se puede modificar desde afuera

**Comment by Alonso-Pablo** [comment]
Duda:

`El nombre de la clave debe ser item`
¿Quiere decir que dentro de la respuesta del `GET` debe haber un objeto con una `key` llamada `Item` y el valor es un objeto que contiene los datos del registro de la tabla de `Items`?

`El endpoint "favorites" debe devolver la lista de favoritos del usuario autenticado (user_id = 1)`
¿Quiere decir que el `GET` tiene que recibir por `Params` un `id` que seria de un `user.id` (tiene que tener un registro en la tabla `Users`)? ¿Y a partir de ese `id` se compara si hay en la tabla `Favorites` un registro con el `user_id` de valor igual?

**Comment by alezvi** [comment]
1) Correcto, pero la key en camel case `item` no `Item`
2) El endpoint de favorites no recibe argumentos, el user lo conoce por la autenticacion, que todavia no lo implementamos. De hecho el `user_id` no tiene que estar en las respuestas. Lo que decía era que a todos los favoritos de la tabla les pongas valor 1 en la columna user_id y dejes armada la consulta poniendo el `user_id = 1`, para que en el futuro cuando tengamos hecho la autenticacion ya puedas cambiar el valor con el user_id real y ya funcione.

**Comment by Alonso-Pablo** [comment]
Duda:

¿El `endpoint` al que se refiere es al GET no?
Si no se necesita pasar el `user_id` porque ya lo tendríamos luego de implementar la autenticación.
Tengo que en POST y el GET siempre tomar como que el usuario que utiliza estos endpoint es el usuario 1 (user_id = 1)
Entonces un ejemplo para hacer un POST de un favorito solo necesitarías el `item_id`. Quedaría así:
```js
{
  "item_id": 28
}
```
Y en GET no necesitariamos pasarle nada por Params, y en el servicio dejamos id que sea 1 (para que cuando se implemente la autenticación se reemplace esa parte)
```ts
  async paginate(options: IPaginationOptions): Promise<Pagination<Favorite>> {
    const favoritesWithItems = this.favoritesRepo
      .createQueryBuilder('favorite')
      .where('favorite.user_id = :id', { id: 1 })
      //...
```
¿?
