### ISSUE TITLE
Feature 15 Cart Documentation and Relation FIX

### ISSUE THREAD

**Issue by Bastian1998** [RooftopAcademy/rooftend#130]
Fixed documentation typo in swagger

Fixed relation oneToMany - manyToOne with cart-items

implemented new method to get all cart-items with the same cart id

**Comment by ChachoPacho** [comment]
### ToDo
- Fix documentation typo in swagger

### Unnecessary
- Fix relation oneToMany - manyToOne with cart-items
- Implement new method to get all cart-items with the same cart id
